name: "Hayuna Pull Request Updater GitHub Action"
description: "GitHub Action that updates a pull request with information extracted from branch name"
author: "Tamim Khan"
runs:
  using: "node12"
  main: "dist/index.js"
inputs:
  repo-token:
    description: "The GITHUB_TOKEN secret"
    required: true
  body-template:
    description: "Body template where branch info gets substituted in"
    required: true
    default: "[%branch%](https://url/to/browse/ticket/%branch%)"
  replace-body:
    description: "Should replace body instead of prefixing"
    required: false
    default: false
branding:
  icon: "edit-3"
  color: "green"
